colorScheme = "slate"
enableCodeCopy = true
enableSearch = true

[footer]
showAppearanceSwitcher = true

[homepage]
showRecent = true
recentLimit = 3
layout = "profile"

[article]
showReadingTime = false
showAuthor = false
showTableOfContents = true
showDate = true            # needed by showTaxonomies
showTaxonomies = true

[list]
groupByYear = false
showTaxonomies = true
invertPagination = true
showDate = true         # needed by showTaxonomies
