colorScheme = "slate"
enableCodeCopy = true
enableSearch = true

[homepage]
showRecent = true
recentLimit = 3

[article]
showReadingTime = false
showAuthor = false
showTableOfContents = true
showDate = true            # needed by showTaxonomies
showTaxonomies = true

[list]
groupByYear = false
