title: Gino's DevOps WiKi
email: pblatorilla@gmail.com
description: >-
  Everything that I know related to DevOps
baseurl: "" 
url: ""
github_username: ginolatorilla

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
